[package]
name = "rshrink"
version = "0.1.0"
edition = "2021"

[dependencies]
magick_rust = "0.16.0"
regex = "1"
num_cpus = "1.0"
eframe = "0.18.0"
rfd = "0.8.2"
# ffmpeg-next = "5.0.3"
# clap = { version = "3.1.8", features = ["derive"] }